name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-1.14.18
      - run: sh -c "$(curl -sSfL https://release.solana.com/v1.14.18/install)"
        shell: bash
        if: steps.cache-solana.outputs.cache-hit != 'true'
      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - run: solana-keygen new --no-bip39-passphrase --force
        shell: bash
      - run: solana config set --url localhost
        shell: bash
